# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b16b83be7ba536572888fb25ded46478"
application_url = "https://fitting-barely-medication-compromise.trycloudflare.com"
embedded = true
name = "testing_bucket"
handle = "testing_bucket"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_orders,read_orders,write_products,read_price_rules,write_price_rules,write_discounts,read_discounts,read_themes,write_themes"

[auth]
redirect_urls = [
  "https://fitting-barely-medication-compromise.trycloudflare.com/auth/callback",
  "https://fitting-barely-medication-compromise.trycloudflare.com/auth/shopify/callback",
  "https://fitting-barely-medication-compromise.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "rohit-cybersify.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
