# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "58227abf1b572fb0200c52086fffff53"
name = "adaptive-vertical-app"
handle = "adaptive-vertical-app-12"
application_url = "https://gg-inclusive-neil-discussed.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "rohit-cybersify.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://gg-inclusive-neil-discussed.trycloudflare.com/auth/callback",
  "https://gg-inclusive-neil-discussed.trycloudflare.com/auth/shopify/callback",
  "https://gg-inclusive-neil-discussed.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
