# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "95ec3e496004fdaa9310abd63f41557a"
application_url = "https://gtk-thanksgiving-guidance-info.trycloudflare.com"
embedded = true
name = "bucket-new-app"
handle = "bucket-new-app"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers,write_customers,read_draft_orders,write_draft_orders,read_products,customer_read_customers,customer_write_customers,customer_read_orders,customer_write_orders,customer_read_draft_orders,write_order_edits,read_order_edits,write_orders,read_orders,read_order_submission_rules,write_order_submission_rules"

[auth]
redirect_urls = [
  "https://gtk-thanksgiving-guidance-info.trycloudflare.com/auth/callback",
  "https://gtk-thanksgiving-guidance-info.trycloudflare.com/auth/shopify/callback",
  "https://gtk-thanksgiving-guidance-info.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "rohit-cybersify.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
